### ISSUE TITLE
how to get highchart js object ?

### ISSUE THREAD

**Issue by ghost** [AngularShowcase/angular2-seed-ng2-highcharts#10]
I'm trying to get the highchart js object the same as we do in js

```
var chart = $('#container').highcharts();
```

And set the xAxis extremes

```
        chart.xAxis[0].setExtremes(
                startTime * 1000,
                endTime * 1000
        );
```

**Comment by Bigous** [comment]
This should be asked at [ng2-highcharts](https://github.com/Bigous/ng2-highcharts) repostory. This is an example project only.

But I've just updated the library to add the `chart()` getter. So, you can use your code just like that.

[]'s
Bigous.
