### ISSUE TITLE
Multiple charts on a page

### ISSUE THREAD

**Issue by rejithomas** [AngularShowcase/angular2-seed-ng2-highcharts#2]
Could there be examples of showing multiple charts on a page? There maybe cases where charts need to be dynamically generated based on some conditions, along with the number of charts to be rendered.

**Comment by Bigous** [comment]
Pull #4 may solve this one. Thanks for using and asking for features!

**Comment by Bigous** [comment]
Pull #4 may solve this.
Thanks for using and contributing with the repo.
