### ISSUE TITLE
Changing type of Chart seems not to work - Only 'line' charts are shown

### ISSUE THREAD

**Issue by EnricoPicci** [AngularShowcase/angular2-seed-ng2-highcharts#3]
I am starting to use ng2-highcharts.
I have been able to use the component within my TestApp but I am not able to get any chart type different from the default one.
For instance, if I change the type of chart to 'column' in the home.ts component of yours, I still get the same chart.
What am I doing wrong?

Thanks in advance
Enrico

**Comment by fergusg** [comment]
I see the same - all charts are "line".  Done some digging but can't work it out.

**Comment by EnricoPicci** [comment]
Use the 2013 version of the js lib (available thtugh Plnkr; if u don't find it i can send u next when i'm back from vacation).
Cioa

**Comment by mgechev** [comment]
@Bigous would you take a look at this?

**Comment by Bigous** [comment]
Hi people, I'll look at it tomorrow. Sorry about the delay.

**Comment by Bigous** [comment]
Pull #4 solves this on the example repo, the bug was on ng2-highcharts - thanks for reporting it.

**Comment by EnricoPicci** [comment]
I have made a couple of changes to the code and it seems to work (i.e.
allow changing type of chart).
Similarly, I have created also a variation to allow use of Highstocks
charts.
Here is the code. I hope it can help.
Ciao
Enrico

_ng2-highcharts.ts_

/// <reference path="../../typings/highcharts/highcharts.d.ts" />

declare var jQuery: any;

import {Directive, ElementRef, Input} from 'angular2/core';

@Directive({
selector: '[ng2-highcharts]'
})
export class Ng2Highcharts {
hostElement: ElementRef;
chart: HighchartsChartObject;

constructor(ele: ElementRef) {
this.hostElement = ele;
}

@Input('ng2-highcharts') set options(opt:HighchartsOptions) {
if(!opt) {
console.log('No valid options...');
console.log(opt);
return;
}
if(opt.series || opt.data) {
            let nativeEl = this.hostElement.nativeElement;
            let jQ = jQuery(nativeEl);
            this.chart = jQ.highcharts(opt);
} else {
console.log('No valid options...');
console.dir(opt);
}
}
}

_ng2-highstocks.ts_

/// <reference path="../../typings/highcharts/highcharts.d.ts" />

declare var jQuery: any;

import {Directive, ElementRef, Input} from 'angular2/core';

@Directive({
    selector: '[ng2-highstocks]'
})
export class Ng2Highstocks {
    hostElement: ElementRef;
    chart: any;

```
constructor(ele: ElementRef) {
    this.hostElement = ele;
}

@Input('ng2-highstocks') set options(opt: any) {
    if (!opt) {
        console.log('No valid options 1 ...');
        console.log(opt);
        return;
    }
    if (opt.series) {
        let nativeEl = this.hostElement.nativeElement;
        let jQ = jQuery(nativeEl);
        this.chart = jQ.highcharts('StockChart', opt);
    } else {
        console.log('No valid options...');
        console.dir(opt);
    }
}
```

}

**Comment by Bigous** [comment]
Hi @EnricoPicci, I'm moving your last comment to ng2-highcharts repo. Thanks.
