### ISSUE TITLE
Questions: How to update bar series data in highcharts?

### ISSUE THREAD

**Issue by born2net** [AngularShowcase/angular2-seed-ng2-highcharts#8]
How to update bar series data in highcharts?
I know you can replace the entire config option but that causes an entire re-render.
I am interested in updating just several bars...

In the original API you do

series.setData(value)
but of course with ng2 there is no reference to the template element so I am wondering what's the proper method...

tx

Sean.

**Comment by born2net** [comment]
well I was able to solve it by getting the chart instance out via @Output

```
if(opt.series || opt.data) {
            if(this.chart) {
                this.chart.destroy();
            }
            if (!opt.chart) {
                opt.chart = {};
            }
            opt.chart.renderTo = this.hostElement.nativeElement;
            this.chart = new Highcharts.Chart(opt);
            this.init.next(this.chart);
        } else {
```

and listen to the init via

```
<div [ng2-highcharts]="_chartBar" (init)="onInit($event)" class="graph"></div>
```

and act upon the chart instance

```
  onInit(event){
        this.series = event.series[0].setData([1,2,3,4,5]);
    }
```

wondering if this is the proper approach ?

tx

Sean.

**Comment by Bigous** [comment]
Hi Sean, you've asked in the ng2-highcharts repo :D sorry about the delay.
