### ISSUE TITLE
How to handle click events on pie/bar chart?

### ISSUE THREAD

**Issue by brijesh-amin** [AngularShowcase/angular2-seed-ng2-highcharts#9]
Hi,
I am trying to handle click events in Ng2HighCharts. HighChart allows me to specify a callback function. However, execution context of this function is different and I can no longer access properties of Angular2 component in the callback function.

**Comment by brijeshamin** [comment]
Hi,
I am trying to handle click events in Ng2HighCharts. HighChart allows me to specify a callback function. However, execution context of this function is different and I can no longer access properties of Angular2 component in the callback function.

**Comment by Bigous** [comment]
Sorry about the delay.

You can setup your events in the option object as you are used in highcharts. Highcharts is still it's own DOM manager - this library is only a wrapper to help to put it in an angular2 application.

I've added an update to the library so you can get the charts object with the `chart` getter to facilitate things.

Questions about the ng2-highcharts should be asked in it's repository. This is only an example repository.

[]'s
Bigous

**Comment by bautistaaa** [comment]
@brijeshamin did you ever figure out how to do this, having same issue with execution context

**Comment by brijesh-amin** [comment]
Hi @bautistaaa ,

Our chart options contain following,

```
      pie: {
        allowPointSelect: false,
        innerSize: '35%',
        cursor: 'pointer',
        size: 150,
        dataLabels: {
          distance: 10,
          format: '{point.name} {point.percentage:.0f} %',
          style: {width: '50px', fontWeight: 'normal', fontSize: '10px'}
        },
        point: {
          events: {
            click: null
          }
        }
      },
```

We have an Angular2 component which contains following in view (html),

```
  <chart [options]="chartOptions" class="ak-piechart-container" (click)="pieClickHandler($event)"
         (load)="chartLoadHandler($event.context)"></chart>
```

ts file contains,

```
  pieClickHandler(event:any) {
       this.pieClicked.emit(event);
   }
```

The above code is just to pass the event to parent component.

In the parent component we have click handler which uses event.point and event.name and redraws chart,

```
  clickHandler(event:any) {
    if (event.point) {
        obj[this.groupingCriteria] = event.point.name;
        obj['text'] = event.point.name;
        obj['type'] = null;
        this.renderChart();
    }
  }
```

**Comment by bautistaaa** [comment]
perfect thank you!
